/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedWithLayoutRouteImport } from './routes/_protected/_with-layout'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedWithLayoutIndexRouteImport } from './routes/_protected/_with-layout/index'
import { Route as ProtectedArticlesIdRouteImport } from './routes/_protected/articles/$id'
import { Route as ProtectedAdminConnectionsRouteImport } from './routes/_protected/admin/connections'
import { Route as ProtectedWithLayoutPrototypeFeedsRouteImport } from './routes/_protected/_with-layout/prototype-feeds'
import { Route as ProtectedWithLayoutManageTagsRouteImport } from './routes/_protected/_with-layout/manage-tags'
import { Route as ProtectedWithLayoutSettingsIndexRouteImport } from './routes/_protected/_with-layout/settings/index'
import { Route as ProtectedWithLayoutArticlesIndexRouteImport } from './routes/_protected/_with-layout/articles/index'
import { Route as ProtectedWithLayoutSettingsImportArticlesIndexRouteImport } from './routes/_protected/_with-layout/settings/import-articles/index'
import { Route as ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport } from './routes/_protected/_with-layout/settings/import-articles/$sessionId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWithLayoutRoute = ProtectedWithLayoutRouteImport.update({
  id: '/_with-layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedWithLayoutIndexRoute =
  ProtectedWithLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedArticlesIdRoute = ProtectedArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminConnectionsRoute =
  ProtectedAdminConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedWithLayoutPrototypeFeedsRoute =
  ProtectedWithLayoutPrototypeFeedsRouteImport.update({
    id: '/prototype-feeds',
    path: '/prototype-feeds',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutManageTagsRoute =
  ProtectedWithLayoutManageTagsRouteImport.update({
    id: '/manage-tags',
    path: '/manage-tags',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsIndexRoute =
  ProtectedWithLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutArticlesIndexRoute =
  ProtectedWithLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsImportArticlesIndexRoute =
  ProtectedWithLayoutSettingsImportArticlesIndexRouteImport.update({
    id: '/settings/import-articles/',
    path: '/settings/import-articles/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsImportArticlesSessionIdRoute =
  ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport.update({
    id: '/settings/import-articles/$sessionId',
    path: '/settings/import-articles/$sessionId',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedWithLayoutIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/prototype-feeds': typeof ProtectedWithLayoutPrototypeFeedsRoute
  '/admin/connections': typeof ProtectedAdminConnectionsRoute
  '/articles/$id': typeof ProtectedArticlesIdRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/articles/': typeof ProtectedWithLayoutArticlesIndexRoute
  '/settings/': typeof ProtectedWithLayoutSettingsIndexRoute
  '/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/settings/import-articles/': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedWithLayoutIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/prototype-feeds': typeof ProtectedWithLayoutPrototypeFeedsRoute
  '/admin/connections': typeof ProtectedAdminConnectionsRoute
  '/articles/$id': typeof ProtectedArticlesIdRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/articles': typeof ProtectedWithLayoutArticlesIndexRoute
  '/settings': typeof ProtectedWithLayoutSettingsIndexRoute
  '/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/settings/import-articles': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/_with-layout': typeof ProtectedWithLayoutRouteWithChildren
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/_with-layout/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/_protected/_with-layout/prototype-feeds': typeof ProtectedWithLayoutPrototypeFeedsRoute
  '/_protected/admin/connections': typeof ProtectedAdminConnectionsRoute
  '/_protected/articles/$id': typeof ProtectedArticlesIdRoute
  '/_protected/_with-layout/': typeof ProtectedWithLayoutIndexRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/_with-layout/articles/': typeof ProtectedWithLayoutArticlesIndexRoute
  '/_protected/_with-layout/settings/': typeof ProtectedWithLayoutSettingsIndexRoute
  '/_protected/_with-layout/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/_protected/_with-layout/settings/import-articles/': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin'
    | '/manage-tags'
    | '/prototype-feeds'
    | '/admin/connections'
    | '/articles/$id'
    | '/admin/'
    | '/articles/'
    | '/settings/'
    | '/settings/import-articles/$sessionId'
    | '/settings/import-articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/manage-tags'
    | '/prototype-feeds'
    | '/admin/connections'
    | '/articles/$id'
    | '/admin'
    | '/articles'
    | '/settings'
    | '/settings/import-articles/$sessionId'
    | '/settings/import-articles'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/_with-layout'
    | '/_protected/admin'
    | '/_protected/_with-layout/manage-tags'
    | '/_protected/_with-layout/prototype-feeds'
    | '/_protected/admin/connections'
    | '/_protected/articles/$id'
    | '/_protected/_with-layout/'
    | '/_protected/admin/'
    | '/_protected/_with-layout/articles/'
    | '/_protected/_with-layout/settings/'
    | '/_protected/_with-layout/settings/import-articles/$sessionId'
    | '/_protected/_with-layout/settings/import-articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_with-layout': {
      id: '/_protected/_with-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedWithLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_with-layout/': {
      id: '/_protected/_with-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedWithLayoutIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/articles/$id': {
      id: '/_protected/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ProtectedArticlesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/connections': {
      id: '/_protected/admin/connections'
      path: '/connections'
      fullPath: '/admin/connections'
      preLoaderRoute: typeof ProtectedAdminConnectionsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/_with-layout/prototype-feeds': {
      id: '/_protected/_with-layout/prototype-feeds'
      path: '/prototype-feeds'
      fullPath: '/prototype-feeds'
      preLoaderRoute: typeof ProtectedWithLayoutPrototypeFeedsRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/manage-tags': {
      id: '/_protected/_with-layout/manage-tags'
      path: '/manage-tags'
      fullPath: '/manage-tags'
      preLoaderRoute: typeof ProtectedWithLayoutManageTagsRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/': {
      id: '/_protected/_with-layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/articles/': {
      id: '/_protected/_with-layout/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ProtectedWithLayoutArticlesIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/import-articles/': {
      id: '/_protected/_with-layout/settings/import-articles/'
      path: '/settings/import-articles'
      fullPath: '/settings/import-articles/'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsImportArticlesIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/import-articles/$sessionId': {
      id: '/_protected/_with-layout/settings/import-articles/$sessionId'
      path: '/settings/import-articles/$sessionId'
      fullPath: '/settings/import-articles/$sessionId'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedWithLayoutRouteChildren {
  ProtectedWithLayoutManageTagsRoute: typeof ProtectedWithLayoutManageTagsRoute
  ProtectedWithLayoutPrototypeFeedsRoute: typeof ProtectedWithLayoutPrototypeFeedsRoute
  ProtectedWithLayoutIndexRoute: typeof ProtectedWithLayoutIndexRoute
  ProtectedWithLayoutArticlesIndexRoute: typeof ProtectedWithLayoutArticlesIndexRoute
  ProtectedWithLayoutSettingsIndexRoute: typeof ProtectedWithLayoutSettingsIndexRoute
  ProtectedWithLayoutSettingsImportArticlesSessionIdRoute: typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  ProtectedWithLayoutSettingsImportArticlesIndexRoute: typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}

const ProtectedWithLayoutRouteChildren: ProtectedWithLayoutRouteChildren = {
  ProtectedWithLayoutManageTagsRoute: ProtectedWithLayoutManageTagsRoute,
  ProtectedWithLayoutPrototypeFeedsRoute:
    ProtectedWithLayoutPrototypeFeedsRoute,
  ProtectedWithLayoutIndexRoute: ProtectedWithLayoutIndexRoute,
  ProtectedWithLayoutArticlesIndexRoute: ProtectedWithLayoutArticlesIndexRoute,
  ProtectedWithLayoutSettingsIndexRoute: ProtectedWithLayoutSettingsIndexRoute,
  ProtectedWithLayoutSettingsImportArticlesSessionIdRoute:
    ProtectedWithLayoutSettingsImportArticlesSessionIdRoute,
  ProtectedWithLayoutSettingsImportArticlesIndexRoute:
    ProtectedWithLayoutSettingsImportArticlesIndexRoute,
}

const ProtectedWithLayoutRouteWithChildren =
  ProtectedWithLayoutRoute._addFileChildren(ProtectedWithLayoutRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminConnectionsRoute: typeof ProtectedAdminConnectionsRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminConnectionsRoute: ProtectedAdminConnectionsRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedWithLayoutRoute: typeof ProtectedWithLayoutRouteWithChildren
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedArticlesIdRoute: typeof ProtectedArticlesIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedWithLayoutRoute: ProtectedWithLayoutRouteWithChildren,
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedArticlesIdRoute: ProtectedArticlesIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
