/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedWithLayoutRouteImport } from './routes/_protected/_with-layout'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as ProtectedWithLayoutIndexRouteImport } from './routes/_protected/_with-layout/index'
import { Route as ProtectedArticlesIdRouteImport } from './routes/_protected/articles/$id'
import { Route as ProtectedWithLayoutManageTagsRouteImport } from './routes/_protected/_with-layout/manage-tags'
import { Route as ProtectedWithLayoutSettingsIndexRouteImport } from './routes/_protected/_with-layout/settings/index'
import { Route as ProtectedWithLayoutArticlesIndexRouteImport } from './routes/_protected/_with-layout/articles/index'
import { Route as ProtectedWithLayoutSettingsImportArticlesIndexRouteImport } from './routes/_protected/_with-layout/settings/import-articles/index'
import { Route as ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport } from './routes/_protected/_with-layout/settings/import-articles/$sessionId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedWithLayoutRoute = ProtectedWithLayoutRouteImport.update({
  id: '/_with-layout',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedWithLayoutIndexRoute =
  ProtectedWithLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedArticlesIdRoute = ProtectedArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedWithLayoutManageTagsRoute =
  ProtectedWithLayoutManageTagsRouteImport.update({
    id: '/manage-tags',
    path: '/manage-tags',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsIndexRoute =
  ProtectedWithLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutArticlesIndexRoute =
  ProtectedWithLayoutArticlesIndexRouteImport.update({
    id: '/articles/',
    path: '/articles/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsImportArticlesIndexRoute =
  ProtectedWithLayoutSettingsImportArticlesIndexRouteImport.update({
    id: '/settings/import-articles/',
    path: '/settings/import-articles/',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)
const ProtectedWithLayoutSettingsImportArticlesSessionIdRoute =
  ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport.update({
    id: '/settings/import-articles/$sessionId',
    path: '/settings/import-articles/$sessionId',
    getParentRoute: () => ProtectedWithLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedWithLayoutIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/articles/$id': typeof ProtectedArticlesIdRoute
  '/articles/': typeof ProtectedWithLayoutArticlesIndexRoute
  '/settings/': typeof ProtectedWithLayoutSettingsIndexRoute
  '/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/settings/import-articles/': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedWithLayoutIndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/articles/$id': typeof ProtectedArticlesIdRoute
  '/articles': typeof ProtectedWithLayoutArticlesIndexRoute
  '/settings': typeof ProtectedWithLayoutSettingsIndexRoute
  '/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/settings/import-articles': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_protected/_with-layout': typeof ProtectedWithLayoutRouteWithChildren
  '/_protected/_with-layout/manage-tags': typeof ProtectedWithLayoutManageTagsRoute
  '/_protected/articles/$id': typeof ProtectedArticlesIdRoute
  '/_protected/_with-layout/': typeof ProtectedWithLayoutIndexRoute
  '/_protected/_with-layout/articles/': typeof ProtectedWithLayoutArticlesIndexRoute
  '/_protected/_with-layout/settings/': typeof ProtectedWithLayoutSettingsIndexRoute
  '/_protected/_with-layout/settings/import-articles/$sessionId': typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  '/_protected/_with-layout/settings/import-articles/': typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/manage-tags'
    | '/articles/$id'
    | '/articles/'
    | '/settings/'
    | '/settings/import-articles/$sessionId'
    | '/settings/import-articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/manage-tags'
    | '/articles/$id'
    | '/articles'
    | '/settings'
    | '/settings/import-articles/$sessionId'
    | '/settings/import-articles'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/login'
    | '/_auth/register'
    | '/_protected/_with-layout'
    | '/_protected/_with-layout/manage-tags'
    | '/_protected/articles/$id'
    | '/_protected/_with-layout/'
    | '/_protected/_with-layout/articles/'
    | '/_protected/_with-layout/settings/'
    | '/_protected/_with-layout/settings/import-articles/$sessionId'
    | '/_protected/_with-layout/settings/import-articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_with-layout': {
      id: '/_protected/_with-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedWithLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_with-layout/': {
      id: '/_protected/_with-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedWithLayoutIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/articles/$id': {
      id: '/_protected/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ProtectedArticlesIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_with-layout/manage-tags': {
      id: '/_protected/_with-layout/manage-tags'
      path: '/manage-tags'
      fullPath: '/manage-tags'
      preLoaderRoute: typeof ProtectedWithLayoutManageTagsRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/': {
      id: '/_protected/_with-layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/articles/': {
      id: '/_protected/_with-layout/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ProtectedWithLayoutArticlesIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/import-articles/': {
      id: '/_protected/_with-layout/settings/import-articles/'
      path: '/settings/import-articles'
      fullPath: '/settings/import-articles/'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsImportArticlesIndexRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
    '/_protected/_with-layout/settings/import-articles/$sessionId': {
      id: '/_protected/_with-layout/settings/import-articles/$sessionId'
      path: '/settings/import-articles/$sessionId'
      fullPath: '/settings/import-articles/$sessionId'
      preLoaderRoute: typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRouteImport
      parentRoute: typeof ProtectedWithLayoutRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedWithLayoutRouteChildren {
  ProtectedWithLayoutManageTagsRoute: typeof ProtectedWithLayoutManageTagsRoute
  ProtectedWithLayoutIndexRoute: typeof ProtectedWithLayoutIndexRoute
  ProtectedWithLayoutArticlesIndexRoute: typeof ProtectedWithLayoutArticlesIndexRoute
  ProtectedWithLayoutSettingsIndexRoute: typeof ProtectedWithLayoutSettingsIndexRoute
  ProtectedWithLayoutSettingsImportArticlesSessionIdRoute: typeof ProtectedWithLayoutSettingsImportArticlesSessionIdRoute
  ProtectedWithLayoutSettingsImportArticlesIndexRoute: typeof ProtectedWithLayoutSettingsImportArticlesIndexRoute
}

const ProtectedWithLayoutRouteChildren: ProtectedWithLayoutRouteChildren = {
  ProtectedWithLayoutManageTagsRoute: ProtectedWithLayoutManageTagsRoute,
  ProtectedWithLayoutIndexRoute: ProtectedWithLayoutIndexRoute,
  ProtectedWithLayoutArticlesIndexRoute: ProtectedWithLayoutArticlesIndexRoute,
  ProtectedWithLayoutSettingsIndexRoute: ProtectedWithLayoutSettingsIndexRoute,
  ProtectedWithLayoutSettingsImportArticlesSessionIdRoute:
    ProtectedWithLayoutSettingsImportArticlesSessionIdRoute,
  ProtectedWithLayoutSettingsImportArticlesIndexRoute:
    ProtectedWithLayoutSettingsImportArticlesIndexRoute,
}

const ProtectedWithLayoutRouteWithChildren =
  ProtectedWithLayoutRoute._addFileChildren(ProtectedWithLayoutRouteChildren)

interface ProtectedRouteChildren {
  ProtectedWithLayoutRoute: typeof ProtectedWithLayoutRouteWithChildren
  ProtectedArticlesIdRoute: typeof ProtectedArticlesIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedWithLayoutRoute: ProtectedWithLayoutRouteWithChildren,
  ProtectedArticlesIdRoute: ProtectedArticlesIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
